[package]
name = "discord-mpd"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]
edition = "2018"

[dependencies]
discord = { git = "https://github.com/io12/discord-rs.git" }
mpd = "0.0.12"
dotenv = "0.13.0"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
log = "0.4.1"
failure = "0.1.1"
itertools = "0.7.8"
romanize = { git = "https://github.com/Bobo1239/romanize.git" }
