cargo-features = ["profile-overrides"]

[package]
name = "discord-mpd"
version = "0.1.0"
authors = ["Boris-Chengbiao Zhou <bobo1239@web.de>"]
edition = "2018"

[dependencies]
mpd = "0.0.12"
dotenv = "0.13.0"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
log = "0.4.1"
failure = "0.1.1"
itertools = "0.7.8"
romanize = { git = "https://github.com/Bobo1239/romanize.git" }
serenity = { version = "0.5.11", features = ["voice"] }
typemap = "0.3.3"
askama = { git = "https://github.com/djc/askama.git", features = ["with-rocket"] }

[build-dependencies]
askama = { git = "https://github.com/djc/askama.git" }

# Enable optimization of dependencies even when using a non-release build as
# igo-rs (from romanize) overflows the stack otherwise.
[profile.dev.overrides."*"]
opt-level = 3
